elementary/switchboard-plug-applications

- src/Startup/Widgets/List.vala
- src/Startup/Widgets/Scrolled.vala
> Switch to placeholder instead of stack

- src/Startup/Backend/DesktopFileEnumerator.vala
- src/Startup/Utils.vala
Just some missing brackets and things
> Code style fixes

- src/Defaults/DefaultPlug.vala
* Bump copyright year
* Remove a bunch of unused labels and replace with a single private class
* Add comboboxes to a size group so that they're all the same width
* Organize
* Fix margins
> DefaultPlug.vala: clean up

- src/Startup/Widgets/AppRow.vala
> Set pixel size for startup apps

- src/Startup/Backend/KeyFile.vala
Fixes https://github.com/elementary/switchboard-plug-applications/issues/18
> Fix missing apps from app chooser

- src/Startup/Widgets/Scrolled.vala
> Scrolled: Replace Gtk.Toolbar

- data/io.elementary.switchboard.applications.appdata.xml.in
For better display in Feedback and AppCenter
> AppData: Add "Settings" to name

- data/io.elementary.switchboard.applications.appdata.xml.in
- src/Startup/Utils.vala
> Fix user's desktop files is not shown

- src/Permissions/Widgets/PermissionSettingsWidget.vala
* Remove unnecessary box
* Rename switch
* Organize
* GObject-style construction
> PermissiongsSettingsWidget: misc cleanup

- src/Permissions/PermissionsPlug.vala
- src/Permissions/Widgets/SidebarRow.vala
- src/meson.build
Make it a lot more obvious what this class is
> Permissions: AppEntry → SidebarRow

- src/Permissions/PermissionsPlug.vala
- src/Permissions/Widgets/PermissionSettingsWidget.vala
> Permissions: Put sidebar in a frame, not paned

- src/Permissions/Backend/App.vala
* ID is actually construct only
* name is purely private set
> App: GObject-style construction

- src/Permissions/Backend/App.vala
> App: Remove single-use get_overrides

- src/Permissions/PermissionsPlug.vala
- src/Permissions/Widgets/AppSettingsView.vala
- src/Permissions/Widgets/PermissionSettingsWidget.vala
* Reset to Defaults is always visible. This is consistent with the action area in Granite.SimpleSettingsPage
* Much easier to keyboard navigate and activate rows
> Permissions: Use ListBox for permissionwidgets

- src/Permissions/Backend/App.vala
This always returns false and thus does nothing
> App: Remove useless overridden_path

- src/Permissions/Backend/App.vala
We don't need to mess with keyfiles for this we have GLib
> App: Get name from AppInfo

- COPYING
- src/Defaults/DefaultPlug.vala
- src/Defaults/Utils.vala
- src/Permissions/Backend/App.vala
- src/Permissions/Backend/AppManager.vala
- src/Permissions/Backend/Permission.vala
- src/Permissions/Backend/PermissionManager.vala
- src/Permissions/Backend/PermissionSettings.vala
- src/Permissions/PermissionsPlug.vala
- src/Permissions/Widgets/AppSettingsView.vala
- src/Permissions/Widgets/PermissionSettingsWidget.vala
- src/Permissions/Widgets/SidebarRow.vala
- src/Plug.vala
- src/Startup/Backend/DesktopFileEnumerator.vala
- src/Startup/Backend/KeyFile.vala
- src/Startup/Backend/KeyFileFactory.vala
- src/Startup/Backend/Monitor.vala
- src/Startup/Controller.vala
- src/Startup/Entities/AppInfo.vala
- src/Startup/Startup.vala
- src/Startup/Utils.vala
- src/Startup/Widgets/AppChooser.vala
- src/Startup/Widgets/AppChooserRow.vala
- src/Startup/Widgets/AppRow.vala
- src/Startup/Widgets/List.vala
- src/Startup/Widgets/Scrolled.vala
Waiting for a comment from Martin (@tchx84) to make sure he's happy with the change
> Relicense as GPL3 and attribute Martin

- src/Permissions/Backend/App.vala
- src/Permissions/Backend/AppManager.vala
> App: construct from flatpak ref

- src/Plug.vala
While we're making string changes, adjusted some others here
> Plug: Add permissions to search results

- src/Permissions/Backend/AppManager.vala
- src/Permissions/PermissionsPlug.vala
- src/Permissions/Widgets/AppSettingsView.vala
We don't need to touch AppManager for this
> Keep selected app in AppSettingsView

- src/Permissions/Widgets/SidebarRow.vala
> SidebarRow: hide description line if blank

- src/Permissions/Backend/App.vala
And make these keyfile warnings debug only since it seems like these files are being created and modified just fine
> App: create overrides folder if it doesn't exist

- src/Startup/Widgets/AppRow.vala
* bump copyright
* New properties syntax
* Granite style class constant
* lambda connect
> Startup/AppRow: Latest codestyle

- src/Startup/Controller.vala
- src/Startup/Widgets/List.vala
- src/Startup/Widgets/Scrolled.vala
* Bump copyright
* construct
* Explicit scope
* Remove single-use functions
* Fix compiler warnings about possible null cast
* Remove non-existent `reload_from_path`
* Lots of braces
> Startup/List: misc cleanup

- src/Startup/Controller.vala
- src/Startup/Startup.vala
Now that we've cleared out some lasagna it's easy to call the controller directly instead of sending signals up through each class
> View/Controller: Use public methods instead of signals

- src/Startup/Controller.vala
- src/Startup/Startup.vala
Why does this class even exist
> Move functions from Controller to Startup

- src/Startup/Backend/KeyFile.vala
- src/Startup/Controller.vala
- src/Startup/Startup.vala
Almost none of these properties are used. These constants just point to other constants. I feel like I'm taking crazy pills
> KeyFile: slim down

- src/Permissions/PermissionsPlug.vala
- Make the app list searchable
- Also instead of showing a placeholder in the applist it now fills the entire grid
Fixes #146 
Screenshot:
> Permissions: Make applist searchable

- src/Permissions/Backend/App.vala
- src/Permissions/PermissionsPlug.vala
- src/Permissions/Widgets/AppSettingsView.vala
- src/Permissions/Widgets/PermissionSettingsWidget.vala
- src/Permissions/Widgets/SidebarRow.vala
> PermissionsPlug: use Switchboard.SettingsPage

- data/icons/32.svg
- data/icons/48.svg
Use the Flatpak symbol to more broadly represent the concept of an application
> Icon: use Flatpak symbol
