src/Startup/Backend/DesktopFileEnumerator.vala, src/Startup/Utils.vala
Hi there :wave: I've started installing some apps on elementary via snap/flatpak since I didn't want to mess with PPAs. However, I couldn't add Spotify to the list of auto-starting apps because its desktop file is not located in `/usr/share/applications`.
So I've changed the app search in the "Startup" tab to search in all app directories found in `$XDG_DATA_DIRS`/`GLib.Environment.get_system_data_dirs` instead. It seems other parts of eOS use Synapse(?) to look for apps, such as the application menu, but I think the list is already better than a single hardcoded path (unless there's a reason for limiting the selection?).
Let me know what you think.
=> Show flatpak/snap apps in auto-start list by searching $XDG-DATA-DIRS

src/Startup/Widgets/AppChooser.vala, src/Startup/Widgets/AppChooserRow.vala
See: https://elementaryos.stackexchange.com/questions/14929/add-startup-app-menu-broken
If there is a better way to limit the text length, please let me know. Maybe there is a way to enforce a width for the Popover?
=> Limit texts length in app chooser

src/Startup/Utils.vala, src/Startup/Widgets/AppChooserRow.vala, src/Startup/Widgets/AppRow.vala
Fixes https://github.com/elementary/switchboard-plug-applications/issues/27 in appchooser. The issue was due to apps using a file path as icon path.. The flatpak issue is no longer reproducible. Tested working for a set of flatpaks, snaps, appimages and debs and manually created deskop files (firefox nightly) with file path.
**Before**
**After**
=> Fix snap icons in AppChooserRow and AppRow

src/Permissions/Widgets/PermissionSettingsWidget.vala
Tiny thing to make this look less broken.
=> PermissionSettingsWidget: Wrap descriptions

src/Permissions/Widgets/AppEntry.vala
Consistent with other sidebars such as notifications settings
=> AppEntry: Use small description label

src/Permissions/Backend/App.vala
`is_negated_permission` is less meaningful than `contains ("=!")`
=> App: Remove one-liner is_negated_permission

src/Permissions/Backend/AppManager.vala, src/Permissions/Widgets/AppSettingsView.vala
After recent updates this plug crashes when opening.
This fixes the immediate cause at least.
=> Fix crash when no selected app.

src/Permissions/PermissionsPlug.vala, src/Permissions/Widgets/AppSettingsView.vala
Listbox will automatically hide and show the placeholder as appropriate, so you don't need to only construct it if the list is empty. But you do need to make sure to call `show_all ()`
I made the whole listbox insensitive instead of just the switch. It's simpler and I think it's more clear too
=> descriptive placeholder, insensitive view

src/Permissions/Widgets/AppSettingsView.vala
This is really nitpicking but I felt it would be better to unify whether to have a trailing period in the same list while translating
=> AppSettingsView: Always have a trailing period for description

src/Permissions/Backend/App.vala, src/Permissions/Backend/AppManager.vala, src/Permissions/Backend/FlatpakManager.vala, src/meson.build
Closes https://github.com/elementary/switchboard-plug-applications/issues/121
=> Permissions view creates empty files in home folder

src/Permissions/Widgets/SidebarRow.vala
The app icon name isn't always necessarily the same thing as the app ID, so we make sure we get the correct icon name from Appinfo
=> SidebarRow: Get icon from appinfo

src/Startup/Entities/AppInfo.vala, src/Startup/Startup.vala
Fixes #134 
Identify duplicate entries by comparing name and path not pointers to the app_info structs (which may differ)
=> Compare app_infos correctly when adding a startup app

src/Defaults/DefaultPlug.vala
Fixes  compile warning `delegates with scope="async" must be owned`
=> DefaultPlug: Explicitly transfer delegate ownership in Thread constructor

src/Defaults/DefaultPlug.vala, src/meson.build
Turns out we've had newer GLib for a while
=> DefaultPlug: Use GLib.get_supported_types ()

data/io.elementary.switchboard.applications.appdata.xml.in, src/Defaults/DefaultPlug.vala, src/Defaults/Utils.vala
Fixes #164 
This PR removes some code that did not seem to serve a useful purpose and was responsible for the linked issue by setting the chosen app as default for types it did not support or were irrelevant by transferring all supported types from the previous default app.
This PR also ensures that type associations are reset before assigning a new default app as it was noticed that the AppChooserButton could otherwise show apps that were not appropriate (did not support the type) if at some point they had been made default for the type (e.g. using FIles or otherwise).
If anyone knows what the original intention of the removed code was please let me know.
=> Ensure app set as default only for supported types

src/Startup/Backend/KeyFile.vala
Very large numbers of critical error messages about missing keys in desktop files are generated at startup, although they do not appear to be critical to the operation of the plug. These are down graded to debug level.
=> Suppress critical messages on startup

src/Defaults/DefaultPlug.vala
We only want the combobox to be focusable, not the whole child
=> Defaults: disallow focusing flowboxchild

src/Defaults/DefaultPlug.vala
When focused, screen reader will read it as "Default `combobox name (e.g Web Browser or Music Player)` combo box. `Application name`"
=> DefaultPlug: Set accessible name for combo boxes

data/applications.metainfo.xml.in, src/Defaults/DefaultPlug.vala
Revert change from #193 
Fixes https://github.com/elementary/music/issues/758
Music does have this content type in the desktop file, but for some reason it's not working
=> DefaultPlug: revert audio content type

src/Permissions/Widgets/AppSettingsView.vala
In the interest of addressing #156 
Also puts the reset button in view since it only effects this box and not the whole view
=> AppSettingsView: add header for sandbox permissions

src/Permissions/Backend/App.vala, src/Permissions/Widgets/AppSettingsView.vala
=> AppSettingsView: use AppInfo description
